services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: ${VAULT_NAME}
    hostname: ${VAULT_NAME}
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=${VAULT_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=587
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=${SMTP_UN}
      - SMTP_PASSWORD=${SMTP_PW}
    ports:
      - "${VAULT_PORT}:443"
    volumes:
      - "${VAULT_VOLUME}:/data"
    networks:
      bw_net:
        ipv4_address: 10.111.0.2
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${DDNS_TZ}
      - SUBDOMAINS=${DDNS_DOMAIN}
      - TOKEN=${DDNS_TOKEN}
    networks:
      vault_net:
        ipv4_address: 10.111.0.3
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${TUNNEL_NAME}
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      vault_net:
        ipv4_address: 10.111.0.4

networks:
  vault_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "10.111.0.0/28"
          gateway: 10.111.0.1

