services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: ${VAULT_NAME}
    hostname: ${VAULT_NAME}
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: DOMAIN_URL}
      ROCKET_PORT: 80 # Internal port for Vaultwarden. Required even with port mapping.
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_UN}
      SMTP_PASSWORD: ${SMTP_PW}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_NAME}
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true # Enable email verification for new signups
      WEB_VAULT_ENABLED: true # Enable the integrated web vault
      WEBAUTHN_ENABLED: true # Enable WebAuthn (for security keys etc.)
      INVITATIONS_ALLOWED: false  # Allow sending organization invitations
      BACKUP_ENABLED: true
      BACKUP_DIR: /data/backups  # Path inside the container
      BACKUP_RETENTION_DAYS: 30
    ports:
      - "${VAULT_PORT}:443"
    volumes:
      - "${VAULT_VOLUME}:/data"
    networks:
      bw_net:
        ipv4_address: 10.111.0.2
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${DDNS_TZ}
      - SUBDOMAINS=${DDNS_DOMAIN}
      - TOKEN=${DDNS_TOKEN}
    networks:
      vault_net:
        ipv4_address: 10.111.0.3
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${TUNNEL_NAME}
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      vault_net:
        ipv4_address: 10.111.0.4

networks:
  vault_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "10.111.0.0/28"
          gateway: 10.111.0.1

