services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: ${VAULT_NAME}
    hostname: ${VAULT_NAME}
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      DOMAIN: ${DOMAIN_URL}
      ROCKET_PORT: 80 # Internal port for Vaultwarden. Required even with port mapping.
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_UN}
      SMTP_PASSWORD: ${SMTP_PW}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_NAME}
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true # Enable email verification for new signups
      WEB_VAULT_ENABLED: true # Enable the integrated web vault
      WEBAUTHN_ENABLED: true # Enable WebAuthn (for security keys etc.)
      INVITATIONS_ALLOWED: false  # Allow sending organization invitations
      BACKUP_ENABLED: true
      BACKUP_DIR: /backups  # Path inside the container
      BACKUP_RETENTION_DAYS: 30
    ports:
      - "${VAULT_PORT}:443"
    volumes:
      - "${VAULT_VOLUME}:/data/"
      - "${VAULT_VOLUME}/backups:/backups/"
      - "${VAULT_VOLUME}/logs:/logs/"
    networks:
      vault_net:
        ipv4_address: 10.111.0.2
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${TUNNEL_NAME}
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      vault_net:
        ipv4_address: 10.111.0.3

  vw_backup:
    image: bruceforce/vaultwarden-backup
    container_name: "${VAULT_NAME}-bak"
    init: true
    environment:
      BACKUP_DIR: /backups/
      BACKUP_DIR_PERMISSIONS: 740  # 700 minimum required
      LOG_DIR: /logs/
      LOG_DIR_PERMISSIONS: 640
      VW_DATABASE_URL: /data/db.sqlite3
      CRON_TIME: 0 5 * * *  # EVERY DAY @ 5am
      DELETE_AFTER: 7
      TIMESTAMP: true
      UID: 0 # enter user that has docker permission (default: root)
      GID: 0 # enter group ID for docker (default: root)
      BACKUP_ADD_DATABASE: true
      BACKUP_ADD_ATTACHMENTS: true
      BACKUP_ADD_CONFIG_JSON: true
      BACKUP_ADD_ICON_CACHE: true
      BACKUP_ADD_RSA_KEY: true
      LOG_LEVEL: info
      TZ: ${TIMEZONE}
    depends_on:
      - vaultwarden
    volumes:
      - "${VAULT_VOLUME}:/data/"
      - "${VAULT_VOLUME}/backups:/backups/"
      - "${VAULT_VOLUME}/logs:/logs/"
    networks:
      vault_net:
        ipv4_address: 10.111.0.4
    restart: unless-stopped

  duckdns:
    image: linuxserver/duckdns:latest
    container_name: "${VAULT_NAME}-dns"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
      SUBDOMAINS: ${DDNS_DOMAIN}
      TOKEN: ${DDNS_TOKEN}
    networks:
      vault_net:
        ipv4_address: 10.111.0.5
    restart: unless-stopped

  cli:
    profiles:
      - extras
    image: bitwarden-cli:latest
    build:
      context: .
      dockerfile: cli.Dockerfile
      args:
        DOMAIN: ${DOMAIN_URL}
    environment:
      DOMAIN: ${DOMAIN_URL}
    depends_on:
      - vaultwarden
    volumes:
      - ${VAULT_VOLUME}:/data
    networks:
      - vault_net

networks:
  vault_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "10.111.0.0/28"
          gateway: 10.111.0.1